name: comfer_wallpaper
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  tray_manager: ^0.5.1
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
